version: "3.2"

services:
    node:
        image: node:latest
        container_name: blueprint-aglio
        user: node
        working_dir: /application
        volumes:
            - .:/application:delegated
        ports:
            - "3000:3000"
